# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04c6fd3a7b5a4b2900261b975edb0f6fc325cc01a9c4f8a83e1edd5abdc22f8b2f5d572229e05e1476738e471fad3b9badc27f724a7b83e778b43338035714a7

test:
  secret_key_base: 80d8a7acd58d4ed2f57532ab94329ca789bf9b9a2c78b74b0960000924f4eb1fd25ac37a9e4687fcf057ee69b55b3125637830dc70d1bacb62b39f57083fc28e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
